### ISSUE TITLE
CI Todo

### ISSUE THREAD

**Issue by vvatelot** [cnumr/EcoIndex_python#54]
- [x] Project quality on merge on main -> Generate Badge
- [x] Push docker images latest when not draft
- [x] Update Docker Images documentation
- [x] Stale action
